name       : liquid-dsp
version    : 1.3.1
release    : 1
source     :
    - https://github.com/jgaeddert/liquid-dsp/archive/v1.3.1.tar.gz : e3f66ce72a3b5d74eea5ccffb049c62c422c91b0ab92d6dbbef21af3c3bfec73
license    : MIT
component  : programming.library
summary    : Digital signal processing library for software-defined radios
description: |
    liquid-dsp is a free and open-source digital signal processing (DSP) library designed specifically for software-defined radios on embedded platforms. The aim is to provide a lightweight DSP library that does not rely on a myriad of external dependencies or proprietary and otherwise cumbersome frameworks. All signal processing elements are designed to be flexible, scalable, and dynamic, including filters, filter design, oscillators, modems, synchronizers, complex mathematical operations, and much more.
builddeps  :
    - pkgconfig(fftw3f)
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-install-libdir-path.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
check      : |
    %make check
